[spine]
spine1 ansible_host=clab-spine-leaf-mini-spine1
spine2 ansible_host=clab-spine-leaf-mini-spine2

[leaf]
leaf1 ansible_host=clab-spine-leaf-mini-leaf1
leaf2 ansible_host=clab-spine-leaf-mini-leaf2
leaf3 ansible_host=clab-spine-leaf-mini-leaf3
leaf4 ansible_host=clab-spine-leaf-mini-leaf4

[ceos:children]
spine
leaf

[ceos:vars]
ansible_user=admin
ansible_connection=network_cli
ansible_network_os=arista.eos.eos
ansible_become=yes
ansible_become_method=enable
